// Command docsgen writes the documentation site's command reference from the
// aos cobra tree, one page per top-level command plus an index. With -check it
// reports drift instead of writing, so `go run ./tools/ci lint` fails like
// `gofmt -l` when the committed pages no longer match the binary.
//
//	go run ./tools/docsgen [outdir]      # write the reference
//	go run ./tools/docsgen -check [dir]  # report drift, exit non-zero on any
//
// It deliberately does not import github.com/spf13/cobra/doc: that package pulls
// go-md2man and blackfriday into the module graph (ADR-0002; go.sum carries both
// today as go.mod-only hashes, so neither is built), its output carries
// "### SEE ALSO" boilerplate, and it cannot emit Starlight frontmatter.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Aman123at/agentic-os/internal/cli"
)

const banner = "{/* Generated by tools/docsgen. Do not edit: `go run ./tools/ci lint` fails on drift. */}"

// defaultOut is relative to the repo root, where `go run ./tools/docsgen` runs.
const defaultOut = "docs-site/src/content/docs/reference"

func main() {
	check := flag.Bool("check", false, "report drift instead of writing (fails like gofmt -l)")
	flag.Parse()
	out := defaultOut
	if flag.NArg() > 0 {
		out = flag.Arg(0)
	}
	pages := generate()
	if *check {
		if err := checkDrift(out, pages); err != nil {
			fail(err)
		}
		return
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		fail(err)
	}
	for name, body := range pages {
		write(filepath.Join(out, name), body)
	}
	fmt.Printf("docsgen: %d pages in %s\n", len(pages), out)
}

// generate walks the command tree and returns the reference as filename->content,
// so the same pages can be written to disk or compared against it.
func generate() map[string]string {
	root := cli.Root()
	var tops []*cobra.Command
	for _, c := range root.Commands() {
		if c.Hidden || c.Name() == "help" || c.Name() == "completion" {
			continue
		}
		tops = append(tops, c)
	}
	sort.Slice(tops, func(i, j int) bool { return tops[i].Name() < tops[j].Name() })

	pages := make(map[string]string, len(tops)+1)
	for _, c := range tops {
		var b strings.Builder
		frontmatter(&b, "aos "+c.Name(), c.Short)
		b.WriteString(banner + "\n\n")
		section(&b, c, 2)
		pages[c.Name()+".mdx"] = b.String()
	}

	var b strings.Builder
	frontmatter(&b, "Command reference", "Every aos command, generated from the binary")
	b.WriteString(banner + "\n\n")
	b.WriteString("Run `aos` with no command to start an interactive chat: each message is a Task.\n\n")
	b.WriteString("| Command | What it does |\n| --- | --- |\n")
	for _, c := range tops {
		fmt.Fprintf(&b, "| [`aos %s`](./%s/) | %s |\n", c.Name(), c.Name(), c.Short)
	}
	pages["index.mdx"] = b.String()
	return pages
}

// checkDrift returns an error naming every reference page that is missing, stale
// or no longer generated (a deleted command leaves a page the tree no longer
// emits). It lists paths one per line like gofmt -l.
func checkDrift(dir string, pages map[string]string) error {
	var drift []string
	for name, want := range pages {
		got, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil || string(got) != want {
			drift = append(drift, filepath.Join(dir, name))
		}
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".mdx") {
			continue
		}
		if _, ok := pages[e.Name()]; !ok {
			drift = append(drift, filepath.Join(dir, e.Name()))
		}
	}
	if len(drift) > 0 {
		sort.Strings(drift)
		return fmt.Errorf("command reference is out of date; run `go run ./tools/docsgen`:\n%s",
			strings.Join(drift, "\n"))
	}
	return nil
}

// section writes one command and recurses into its subcommands, so a group like
// `aos service` stays on one page instead of scattering into a directory.
func section(b *strings.Builder, c *cobra.Command, level int) {
	if level > 2 {
		fmt.Fprintf(b, "%s `%s`\n\n", strings.Repeat("#", level), c.CommandPath())
	}
	if long := strings.TrimSpace(c.Long); long != "" {
		fmt.Fprintf(b, "%s\n\n", long)
	} else if short := strings.TrimSpace(c.Short); short != "" {
		fmt.Fprintf(b, "%s\n\n", short)
	}
	// A group with no RunE has nothing to run, so its usage line is noise.
	if c.Runnable() {
		fmt.Fprintf(b, "```\n%s\n```\n\n", strings.TrimSpace(c.UseLine()))
	}
	if flags := strings.TrimRight(c.NonInheritedFlags().FlagUsages(), "\n"); flags != "" {
		fmt.Fprintf(b, "Options:\n\n```\n%s\n```\n\n", flags)
	}
	if ex := strings.TrimSpace(c.Example); ex != "" {
		fmt.Fprintf(b, "Example:\n\n```sh\n%s\n```\n\n", ex)
	}
	subs := c.Commands()
	sort.Slice(subs, func(i, j int) bool { return subs[i].Name() < subs[j].Name() })
	for _, s := range subs {
		if s.Hidden || s.Name() == "help" {
			continue
		}
		section(b, s, level+1)
	}
}

func frontmatter(b *strings.Builder, title, description string) {
	fmt.Fprintf(b, "---\ntitle: %s\ndescription: %s\n---\n\n", yamlString(title), yamlString(description))
}

// yamlString quotes a scalar the blunt way: the strings here are command help,
// never multi-line, and a generator that guesses wrong produces a site that
// does not build.
func yamlString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(strings.TrimSpace(s)) + `"`
}

func write(path, body string) {
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "docsgen:", err)
	os.Exit(1)
}
